services:
  postgres:
    image: postgres:alpine
    env_file: ./docker/postgres/.env.local
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
